resources:
- ../../../../webhook-admission

configurations:
- kustomizeconfig.yaml

patchesStrategicMerge:
- admission_configurations_url_patch.yaml

# the following config is for teaching kustomize how to do var substitution
vars:
  - name: NAMESPACE # namespace of the service
    objref:
      kind: Service
      version: v1
      name: webhook-service
    fieldref:
      fieldpath: metadata.namespace
  - name: SERVICENAME
    objref:
      kind: Service
      version: v1
      name: webhook-service
