version = 1
SPDX-PackageName = "Gardener terminal-controller-manager"
SPDX-PackageSupplier = "The Gardener project <gardener@googlegroups.com>"
SPDX-PackageDownloadLocation = "https://github.com/gardener/terminal-controller-manager"

[[annotations]]
path = [
  ".ci/**",
  ".github/**",
  "charts/**/Chart.yaml",
  "charts/**/values.yaml",
  "charts/**/templates/**.yaml",
  "charts/**/templates/**/**.yaml",
  "charts/terminal/charts/application/crd-gen/**.yaml",
  ".dockerignore",
  ".gimps.yaml",
  ".gitignore",
  ".golangci.yaml",
  "CODEOWNERS",
  "go.mod",
  "go.sum",
  "**.json",
  "**.tpl",
  "VERSION"
]
precedence = "aggregate"
SPDX-FileCopyrightText = "2021-2024 SAP SE or an SAP affiliate company and Gardener contributors"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = ["**.md"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2021-2024 SAP SE or an SAP affiliate company and Gardener contributors"
SPDX-License-Identifier = "CC-BY-4.0"
