apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- manager.yaml

images:
- name: controller
  newName: psutter/dashboard-terminal
  newTag: go1.14

configMapGenerator:
- files:
  - config.yaml
  name: controller-manager-configmap
