apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- manager.yaml

images:
- name: controller
  newName: eu.gcr.io/gardener-project/gardener/terminal-controller-manager
  newTag: latest
- name: gcr.io/kubebuilder/kube-rbac-proxy
  newName: gcr.io/kubebuilder/kube-rbac-proxy
  newTag: v0.4.0
- name: kuberbacproxy
  newName: rbacproxy
  newTag: "0.1"
