apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- manager.yaml

images:
- name: controller
  newName: eu.gcr.io/gardener-project/gardener/terminal-controller-manager
  newTag: latest

configMapGenerator:
- files:
  - config.yaml
  name: controller-manager-configmap
