# SPDX-FileCopyrightText: 2021 SAP SE or an SAP affiliate company and Gardener contributors
#
# SPDX-License-Identifier: Apache-2.0

# Adds namespace to all resources.
namespace: terminal-system

namePrefix: terminal- # must match with namePrefix defined in ../../default/kustomization.yaml

commonLabels:
  component: terminal-manager

resources:
- manager
- ../../../rbac-rt
