# use hack/gen-certs script to generate the certificates or provide your own certificates

secretGenerator:
  - name: webhook-server-cert
    namespace: system
    files:
      - tls.crt=tls/terminal-controller-manager-tls.pem
      - tls.key=tls/terminal-controller-manager-tls-key.pem
    type: "kubernetes.io/tls"
