# SPDX-FileCopyrightText: 2021 SAP SE or an SAP affiliate company and Gardener contributors
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: dashboard.gardener.cloud/v1alpha1
kind: Terminal
metadata:
  annotations:
    dashboard.gardener.cloud/operation: keepalive
  namespace: garden-coretmp
  name: term-lukas-hib-deprecated
spec:
  host:
    credentials:
      serviceAccountRef:
        name: seed-myseed
        namespace: gardentmp
    namespace: shoot--core--mycluster
    pod:
      containerImage: eu.gcr.io/gardener-project/gardener/ops-toolbelt:0.11.0
  target:
    credentials:
      serviceAccountRef:
        name: lukas-hib.kubeconfig
        namespace: garden-coretmp
    kubeconfigContextNamespace: default
    temporaryNamespace: true
    bindingKind: ClusterRoleBinding
    roleName: cluster-admin
