# uncomment lines below and provide caBundle with sensible data. Alternatively use certmanager to inject the caBundle

#apiVersion: admissionregistration.k8s.io/v1beta1
#kind: MutatingWebhookConfiguration
#metadata:
#  name: mutating-webhook-configuration
#webhooks:
#  - clientConfig:
#      caBundle: Cg==
#    name: mutating-create-update-terminal.gardener.cloud
#---
#apiVersion: admissionregistration.k8s.io/v1beta1
#kind: ValidatingWebhookConfiguration
#metadata:
#  name: validating-webhook-configuration
#webhooks:
#  - clientConfig:
#      caBundle: Cg==
#    name: validating-create-update-terminal.gardener.cloud
