# uncomment the lines below and provide kubeconfig with sensible data. Generate a new kubeconfig pointing to the virtual-garden and use the token from the controller-manager's default service account residing in the virtual garden

#apiVersion: v1
#kind: Secret
#type: opage
#metadata:
#  name: kubeconfig
#  namespace: system
#data:
#  kubeconfig: Cg==
