apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
  namespace: system
spec:
  template:
    spec:
      containers:
      - name: kube-rbac-proxy
        volumeMounts: # TODO this will replace the list, how to merge/add to list?
          - name: terminal-controller-secret-kubeconfig
            mountPath: /etc/gardener-terminal-controller/secrets/kubeconfig
            readOnly: true
      volumes:
        - name: terminal-controller-secret-kubeconfig
          secret:
            secretName: kubeconfig
