apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
webhooks:
  - clientConfig:
      service:
        name: webhook-service
        namespace: system
        path: /mutate-terminal
      url: null
    name: mutating-create-update-terminal.gardener.cloud
---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
  - clientConfig:
      service:
        name: webhook-service
        namespace: system
        path: /validate-terminal
      url: null
    name: validating-create-update-terminal.gardener.cloud
