# Adds namespace to all resources.
namespace: terminal-system

namePrefix: terminal- # must match with namePrefix defined in ../../default/kustomization.yaml

commonLabels:
  component: terminal-manager

resources:
- ../../default
- ../../crd
- ../../rbac
- ../../rbac-rt
- ../../secret
- webhook-admission
- manager

vars:
  - name: TLSCERT # somehow this var cannot be defined in the config/webhook-admission/kustomization.yaml
    objref:
      kind: Secret
      version: v1
      name: webhook-server-cert
    fieldref:
      fieldpath: data[tls.crt]
